model_name: meta-llama/Llama-3-8B-Instruct
eos_token: <|end_of_text|>
words: data/CREA_10k/4-CREA_10k_lemmas.tsv
iter: 11-final
prompts: prompts/llama/v9.json
num_words: 4594
categories: False
batch_size_def: 15
batch_size_words: 15
stop_strings: "}"