model_name: bertin-project/Gromenauer-7B-Instruct
eos_token: </s>
words: data/DEA_100/100_palabras_DEA_v5.tsv
iter: 11-final
prompts: prompts/llama/v9.json
num_words: 100
categories: False
batch_size_def: 20
batch_size_words: 20
stop_strings: "}"