model_name: meta-llama/Llama-2-7b-chat-hf
eos_token: </s>
words: data/DEA_100/100_palabras_DEA_v5.tsv
iter: 11-final
prompts: prompts/llama/v9.json
num_words: 100
categories: False
batch_size_def: 10
batch_size_words: 10
stop_strings: "}"