model_name: meta-llama/Llama-3.1-8B-Instruct
eos_token: <|eot_id|>
words: data/CREA_10k-v2/3-CREA_10k_pos_filter.tsv
iter: 10-updated-anon
prompts: prompts/no_cat/llama/v9.json
num_words: 4594
categories: False
batch_size_def: 8
batch_size_words: 16
stop_strings: "}"