model_name: google/gemma-7b-it
eos_token: <end_of_turn>
words: data/CREA_10k-v2/3-CREA_10k_pos_filter.tsv
iter: 11-final
prompts: prompts/no_cat/mistral/v9.json
num_words: 7784
categories: False
batch_size_def: 8
batch_size_words: 16
stop_strings: "}"